services:
  - type: web
    name: ark-systems-website
    env: static
    staticPublishPath: out
    buildCommand: npm install && npm run build
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
